int get_choice(char *);
void choose_find();
void choose_new_person();
void choose_get_person();
void choose_list_people();
void choose_new_place();
void choose_list_places();
void work_with_person(struct person *);
struct person *choose_from_list_of_people(struct person *, int);
void chomp(char *);
